---
- name: restart docker service by systemd
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  listen: "restart docker"
  when: ansible_service_mgr == "systemd"

- name: restart docker service
  service:
    name: docker
    state: restarted
  listen: "restart docker"
  when: ansible_service_mgr != "systemd"
